apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: vote
    tier: front
  name: rollout-vote
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vote
  strategy:
    blueGreen:
      activeService: vote
      previewService: vote-preview
      autoPromotionEnabled: true
      autoPromotionSeconds: 60
  template:
    metadata:
      labels:
        app: vote
        tier: front
    spec:
      containers:
      - image: docker-registry-remote.artifactory-espoo2.int.net.nokia.com/schoolofdevops/vote:v5
        name: vote
        imagePullPolicy: IfNotPresent
        resources: 
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits: 
            cpu: "250m"
            memory: "128Mi"

